
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes




- name: "deploy role - start the app"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- run start