version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      # Add parameter here
      stackname:
        type: string   
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name <<parameters.stackname>>
 
         
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
            npm audit fix
            npm update
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [test-frontend]
      - run:
          name: Run test-frontend
          command: |
             cd frontend
             npm install
             npm run test
      - save_cache:
          paths: [frontend/test]
          key: test-frontend
                
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [test-backend]
      - run:
          name: Run test-backend
          command: |
             cd backend
             npm install
             npm run test
      - save_cache:
          paths: [backend/test]
          key: test-backend     

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-frontend]
      - run:
          name: Run scan-frontend
          command: |
             cd frontend
             npm install
             npm audit fix --audit-level=critical
           #  npm audit --audit-level=critical


  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [scan-backend]
      - run:
          name: Run scan-backend
          command: |
             cd backend
             npm install
             npm audit fix --audit-level=critical 
            #npm audit --audit-level=critical


  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli # Docker image here that supports AWS CLI
    steps:
      - checkout  
      - run:
          name: Install tar and gzip
          command: 

                yum install -y tar gzip        
      - run:
          name: Ensure back-end infrastructure exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/backend.yml \
              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
              --tags project=udapeople 
          # exit 1
      - run:
          name: Ensure front-end infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/frontend.yml \
              --tags project=udapeople-frontend \
              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" 
          #exit 1
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            echo "[web]" >> backend/inventory.txt
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> backend/inventory.txt
              cat backend/inventory.txt
      - persist_to_workspace:
          root: backend
          paths:
            - inventory.txt
      - destroy-environment:
          stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
      - destroy-environment:
          stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
      # Here's where you will add some code to rollback on failure   

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11  #, amazon/aws-cli]
    steps:
      # Checkout code from git
      - checkout
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints: ["4e:27:4b:b1:89:2e:f2:9a:22:b2:2b:8e:db:39:e8:ab"]
      # attach workspace
      - attach_workspace:
          at: ~/project 
      - run:
          name: Install dependencies
          command: |
            apk update
            apk upgrade
            apk add tar gzip
            python -m pip install --upgrade pip
            pip install awscli --upgrade
            apk add --update ansible
          #exit 1
      - run:
          name: Check back-end ip and save to ansible inventory
          command: |

            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> .circleci/ansible/inventory.txt
              cat .circleci/ansible/inventory.txt
      - run:
          name: Configure server  
          command: |
            cd .circleci/ansible
            export ANSIBLE_HOST_KEY_CHECKING=False

            ansible-playbook -i inventory.txt configure-server.yml
          #  exit 1
      # Here's where you will add some code to rollback on failure      


  run-migrations:
    docker:
      - image: circleci/node:14.18.1
    steps:
      # Checkout code from git
      - checkout
      - run:
          name: Run migrations
          command: |
            cd backend
            npm install
            npm run migrations > migrations_dump.txt

          #  exit 1
      - run:
          name: Send migration results to memstash
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
                curl https://kvdb.io/FS3hVsEzwoNt2BqndJbxfb/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'

            fi
          # 
          #  exit 1
     # Here's where you will add some code to rollback on failure 
      - destroy-environment:
          stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
      - destroy-environment:
          stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
  deploy-frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      # Checkout code from git
      - checkout   
      - run:
          name: Install dependencies  tar gzip
          command: |
            yum install -y tar gzip
      - run:
          name: Install dependencies nodejs
          command: |
            cd frontend
            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
            yum -y install nodejs
      - run:
          name: Install dependencies awscli
          command: |
            yum -y install awscli

      - run:
          name: Get backend url
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            export API_URL="http://${BACKEND_IP}:3030" 
            echo "API_URL = ${API_URL}"
            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
            cat frontend/.env
            echo ENVIRONMENT=production > ".env"

      - run:
          name: Deploy frontend objects
          command: |
            cd frontend
            npm install
            npm run build
            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive

      # Here's where you will add some code to rollback on failure 
      - destroy-environment:
          stackname: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
      - destroy-environment:
          stackname: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11 # Docker image here that supports Ansible
    steps:
      # Checkout code from git
      - checkout
      # Add ssh keys with fingerprint
      - add_ssh_keys:
          fingerprints: ["4e:27:4b:b1:89:2e:f2:9a:22:b2:2b:8e:db:39:e8:ab"]
      # attach workspace
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies deploy-backend
          command: |
            apk add openssh-client
            apk add --update ansible curl rsync openssh nodejs npm
            ansible --version
            pip install awscli
            pip install --upgrade pip
            aws --version
      - run:
          name: Deploy backend
          command: |
            cd backend
            npm install
            npm run build
            pwd
            cd ..
            tar -C backend -czvf artifact.tar.gz .
            pwd
            echo "[web]" >> /root/project/backend/inventory.txt
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> /root/project/backend/inventory.txt
            cd .circleci/ansible
            echo "Contents  of the inventory.txt file is -------"

              cat /root/project/backend/inventory.txt
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i /root/project/backend/inventory.txt deploy-backend.yml
      # Here's where you will add some code to rollback on failure 
  
  smoke-test:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: 
          name: dependences
          command: |
            apk add --update curl nodejs npm
            pip install awscli
      - run:
          name: smoke test - backend           #  export API_URL="http://${BACKEND_IP}:3030"
          command: |
            export BACKEND_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text)
            export API_URL="http://${BACKEND_IP}:3030"  
            echo "${API_URL}"
         

            if curl "${API_URL}/api/status" | grep "ok"
            then
              return 0
            else
              return 1
            fi      
      - run:
          name: smoke test - frontend
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
            echo ${URL} 
            if curl -s ${URL} | grep "Welcome"
            then
            return 1
            else
            return 1
            fi

workflows:
  default:
    jobs:
#      - build-frontend
#      - build-backend
    #  - test-frontend:
    #      requires: [build-frontend]
    #  - test-backend:
    #      requires: [build-backend]
    #  - scan-frontend:
    #      requires: [build-frontend]
    #  - scan-backend:
    #      requires: [build-backend]
#      - deploy-infrastructure:
#          requires: [build-frontend, build-backend]
    #      requires: [test-frontend, test-backend, scan-frontend, scan-backend]
      - configure-infrastructure
#          requires: [deploy-infrastructure]
#      - run-migrations:
#          requires: [configure-infrastructure]
#      - deploy-frontend:
#          requires: [run-migrations]
#      - deploy-backend:
#          requires: [run-migrations]
        #  requires: [configure-infrastructure]
#      - smoke-test:
#          requires: [deploy-backend, deploy-frontend]
        #  requires: [deploy-backend]